@startuml name "Domain Model"

package "shared-kernel.model" {
    class Candidate {
        +_id: string
        +_name: string
        +_firstName: string
        +_dateOfBirth: Date
        +_experience: number
        +_skills: string[]
        +_softSkills: string
        +_cvPath: string
        +_source: string
        +_cooptation: boolean
        +_coopter: string
        +_info: Map<string, object>
    }

    class Recruiter {
        +_id: string
        +_name: string
        +_firstName: string
        +_dateOfBirth: Date
        +_experience: number
        +_skills: string[]
        +_softSkills: string
        +_availabilities: Date[]
        +_iban: string
        +_salary: number
        +_address: string
        +_seniority: Date
        +_idCart: string
        +_interviews: number
        +_info: Map<string, object>
        +getId(): string
        +getAvailabilities(): Date[]

    }

    class Space {
        +_id: string
        +_name: string
        +_location: string
        +_capacity: number
        +_address: string
        +_equipments: string[]
        +_participants: string
        +_availabilities: Date[]
        +_info: Map<string, object>
    }

    Space *--> Recruiter : _owner
    Recruiter <--* Candidate : _inteviewer
    Candidate "*" <--* Recruiter : _candidates
}

package "let-me-be-free.model.interview" {
    interface RecruiterRepository {
        +findAll(): HRRecruiter[]
    }

    interface RoomRepository {
        +book(date: InterviewDate): Space
        +cancel(spaceId: string): void
    }

    class Interview {
        +_date: InterviewDate
        + getRecruiter(): HRRecruiter
        + getCandidate(): HRCandidate
        + getInterviewDate(): InterviewDate
        + getRoom(): Room
    }

    class InterviewDate {
        -_date: Date;
        + getDate(): Date
        + checkDate(): void | never
        + equals(other: InterviewDate): boolean 
    }

    class Room {
        +_room: Space
        +getCapacity(): number
        +getEquipments(): string[]
        +getAddress(): string
        +checkRoom(): void
    }

    class HRRecruiter {
        -_recruiter: Recruiter
        + isAvailable(interviewDate: InterviewDate): boolean
        + canTest(candidate: HRCandidate): boolean
        + book(interviewDate: InterviewDate): void
        + getAvailabilities(): InterviewDate[]
        + getSkills(): string[]
        + getId(): string
        + getName(): string
        + getFirstName(): string
    }

    class HRCandidate {
        -_candidate: Candidate
        +getId(): string
        +getSkills(): string[]
        +checkCandidate(): void | never
        +findRecruiter(date: InterviewDate, recruiters: HRRecruiter[]): HRRecruiter | never

    }

    class FakeRoomRepository extends RoomRepository {
        +book(date: InterviewDate): Space
        +cancel(spaceId: string): void
    }

    class FakeRecruiterRepository extends RecruiterRepository {
        +findAll(): HRRecruiter[]
    }

    FakeRecruiterRepository *--> "*" Recruiter : _recruiters
    Interview *--> Recruiter : _recruiter
    Interview *--> Candidate : _candidate
    Interview *--> Space : _room
}

package "let-me-be-free.use_case" {
    class PlanInterview {
        +_recruiters: RecruiterRepository
        +_rooms: RoomRepository
        +scheduleInterview(interviewDate: Date, candidate: Candidate): Interview
    }

    PlanInterview *--> RecruiterRepository : _recruiters
    PlanInterview *--> RoomRepository : _rooms
}
@enduml